package com.example.yenisozluk;

public class kelime_array {

    public String renken(int tek) {
        String a[]={"Red","Blue","Green","Yellow","Pink","Purple","Black","Brown","Orange","White","Gray",null};
        return a[tek];
    }
    public String renktr(int tek) {
        String a[]={"Kırmızı","Mavi","Yeşil","Sarı","Pembe","Mor","Siyah","Kahverengi","Turuncu","Beyaz","Gri",null};
        return a[tek];
    }
    public String populeren(int tek) {
        String a[]={"a",
                "able","about","above","across","act","action","actually","add","addition","adjective","afraid","Africa","after","again","against","age","ago","agreed","ahead","air","all","allow","almost","alone","along","already","also","although","always","am","America","among","amount","an","and","angle","animal","another","answer","any","anything","appear",
                "apple","are","area","arms","army","around","arrived","art","as","ask","at","away","baby","back","bad","ball","bank","base","be","bear","beat","beautiful","became","because","become","bed","been","before","began","begin","behind","being","believe","bell","belong","below","beside","best","better","between","big","bill","birds","bit","black","block","blood","blow","blue","board","boat","body","bone","book","born","both","bottom","box","boy","branch","break","bright","bring","British","broken","brother","brought","brown","build","building","built","burn","business","but","buy","by","call","came","can","cannot","can't","capital","captain","car","care","carefully","carry","case","cat","catch","cattle","caught","cause","cell","center","cent","century","certain","chance","change","chart","check","chief","child","children","choose","church","circle","city","class","clean","clear",
                "climb",
                "close",
                "cloth",
                "cloud",
                "coast",
                "cold",
                "color",
                "column",
                "come",
                "common",
                "company",
                "compare",
                "complete",
                "compound",
                "condition",
                "consider",
                "consonant",
                "contain",
                "continue",
                "control",
                "cook",
                "cool",
                "copy",
                "corn",
                "corner",
                "correct",
                "cost",
                "cotton",
                "could",
                "couldn't",
                "count",
                "country",
                "course",
                "cover",
                "cow",
                "create",
                "cry",
                "crop",
                "cross",
                "crowd",
                "current",
                "cut",
                "dance",
                "dark",
                "day",
                "dead",
                "deal",
                "death",
                "decide",
                "decimal",
                "deep",
                "describe",
                "desert",
                "design",
                "details",
                "determine",
                "develope",
                "dictionary",
                "did",
                "didn't",
                "died",
                "difference",
                "different",
                "difficult",
                "direct",
                "direction",
                "discover",
                "distance",
                "divided",
                "division",
                "do",
                "doctor",
                "does",
                "doesn't",
                "dog",
                "dollar",
                "done",
                "don't",
                "door",
                "down",
                "draw",
                "drawing",
                "dress",
                "drive",
                "drop",
                "dry",
                "during",
                "each",
                "early",
                "ear",
                "earth",
                "east",
                "easy",
                "eat",
                "edge",
                "effect",
                "egg",
                "eight",
                "either",
                "electric",
                "element",
                "else",
                "end",
                "energy",
                "engine",
                "England",
                "English",
                "enjoy",
                "enough",
                "enter",
                "entire",
                "equal",
                "equation",
                "especially",
                "Europe",
                "even",
                "evening",
                "ever",
                "every",
                "everyone",
                "everything",
                "exactly",
                "example",
                "except",
                "exciting",
                "exercise",
                "expect",
                "experience",
                "experiment",
                "explain",
                "express",
                "eye",
                "face",
                "fact",
                "factoriy",
                "factors",
                "fall",
                "family",
                "famous",
                "far",
                "farm",
                "farmer",
                "fast",
                "father",
                "fear",
                "feel",
                "feeling",
                "feet",
                "fell",
                "felt",
                "few",
                "field",
                "fig",
                "fight",
                "figure",
                "filled",
                "finally",
                "find",
                "fine",
                "fingers",
                "finished",
                "fire",
                "first",
                "fish",
                "fit",
                "five",
                "flat",
                "floor",
                "flow",
                "flowers",
                "fly",
                "follow",
                "food",
                "foot",
                "for",
                "force",
                "forest",
                "form",
                "forward",
                "found",
                "four",
                "fraction",
                "France",
                "free",
                "French",
                "fresh",
                "friends",
                "from",
                "front",
                "fruit",
                "full",
                "fun",
                "game",
                "garden",
                "gas",
                "gave",
                "general",
                "get",
                "girl",
                "give",
                "glass",
                "go",
                "God",
                "gold",
                "gone",
                "good",
                "got",
                "government",
                "grass",
                "great",
                "Greek",
                "green",
                "grew",
                "ground",
                "group",
                "grow",
                "guess",
                "gun",
                "had",
                "hair",
                "halt",
                "hand",
                "happen",
                "happy",
                "hard",
                "has",
                "hat",
                "have",
                "he",
                "head",
                "hear",
                "heard",
                "heart",
                "heat",
                "heavy",
                "held",
                "help",
                "her",
                "here",
                "high",
                "hill",
                "him",
                "himself",
                "his",
                "history",
                "hit",
                "hold",
                "hole",
                "home",
                "hope",
                "horse",
                "hot",
                "hour",
                "house",
                "how",
                "however",
                "huge",
                "human",
                "hundred",
                "hunting",
                "I",
                "ice",
                "idea",
                "if",
                "I'll",
                "important",
                "in",
                "inches",
                "include",
                "increase",
                "Indian",
                "indicate",
                "industry",
                "information",
                "insect",
                "inside",
                "instead",
                "instruments",
                "interest",
                "interesting",
                "into",
                "iron",
                "is",
                "island",
                "isn't",
                "it",
                "its",
                "it's",
                "itself",
                "Japanese",
                "job",
                "join",
                "jump",
                "just",
                "keep",
                "kept",
                "key",
                "kill",
                "kind",
                "king",
                "knew",
                "know",
                "known",
                "lady",
                "lake",
                "land",
                "language",
                "large",
                "last",
                "later",
                "laugh",
                "law",
                "lay",
                "lead",
                "learn",
                "least",
                "leave",
                "led",
                "left",
                "leg",
                "length",
                "less",
                "let",
                "let's",
                "letter",
                "level",
                "lie",
                "life",
                "lift",
                "light",
                "like",
                "line",
                "list",
                "listen",
                "little",
                "live",
                "location",
                "long",
                "look",
                "lost",
                "lot",
                "loud",
                "love",
                "low",
                "machine",
                "made",
                "main",
                "major",
                "make",
                "man",
                "many",
                "map",
                "march",
                "mark",
                "match",
                "material",
                "matter",
                "may",
                "maybe",
                "me",
                "mean",
                "measure",
                "meat",
                "meet",
                "melody",
                "member",
                "men",
                "metal",
                "method",
                "middle",
                "might",
                "mile",
                "milk",
                "million",
                "mind",
                "mine",
                "minute",
                "miss",
                "modern",
                "molecules",
                "moment",
                "money",
                "month",
                "moon",
                "more",
                "morning",
                "most",
                "mother",
                "mountain",
                "mouth",
                "move",
                "movement",
                "much",
                "music",
                "must",
                "my",
                "name",
                "nation",
                "natural",
                "near",
                "necessary",
                "need",
                "never",
                "new",
                "next",
                "night",
                "no",
                "nor",
                "north",
                "northern",
                "nose",
                "not",
                "note",
                "nothing",
                "notice",
                "noun",
                "now",
                "number",
                "numeral",
                "object",
                "observe",
                "ocean",
                "of",
                "off",
                "office",
                "often",
                "oh",
                "oil",
                "old",
                "on",
                "once",
                "one",
                "only",
                "open",
                "opposite",
                "or",
                "order",
                "other",
                "our",
                "out",
                "outside",
                "over",
                "own",
                "oxygen",
                "page",
                "paint",
                "pair",
                "paper",
                "paragraph",
                "park",
                "part",
                "particular",
                "party",
                "passed",
                "past",
                "pattern",
                "pay",
                "people",
                "per",
                "perhaps",
                "period",
                "person",
                "phrase",
                "pick",
                "picture",
                "piece",
                "place",
                "plain",
                "plan",
                "plane",
                "plant",
                "plants",
                "play",
                "please",
                "plural",
                "poem",
                "point",
                "pole",
                "poor",
                "position",
                "possible",
                "pound",
                "power",
                "practice",
                "prepare",
                "president",
                "pretty",
                "printed",
                "probably",
                "problem",
                "process",
                "produce",
                "product",
                "property",
                "provide",
                "pull",
                "push",
                "put",
                "question",
                "quickly",
                "quiet",
                "quite",
                "race",
                "radio",
                "rain",
                "raise",
                "ran",
                "rather",
                "reach",
                "read",
                "ready",
                "really",
                "reason",
                "receive",
                "record",
                "red",
                "region",
                "remain",
                "remember",
                "repeat",
                "report",
                "represent",
                "resent",
                "rest",
                "result",
                "return",
                "rhythm",
                "rich",
                "ride",
                "right",
                "ring",
                "rise",
                "river",
                "road",
                "rock",
                "rolled",
                "room",
                "root",
                "rope",
                "rose",
                "round",
                "row",
                "rule",
                "run",
                "safe",
                "said",
                "sail",
                "same",
                "sand",
                "sat",
                "save",
                "saw",
                "say",
                "scale",
                "school",
                "science",
                "scientist",
                "score",
                "sea",
                "seat",
                "second",
                "section",
                "see",
                "seed",
                "seem",
                "seen",
                "sell",
                "send",
                "sense",
                "sent",
                "sentence",
                "separate",
                "serve",
                "set",
                "settled",
                "seven",
                "several",
                "shall",
                "shape",
                "sharp",
                "she",
                "ship",
                "shoes",
                "shop",
                "short",
                "should",
                "shoulder",
                "shout",
                "show",
                "shown",
                "side",
                "sight",
                "sign",
                "signal",
                "silent",
                "similar",
                "simple",
                "since",
                "sing",
                "sir",
                "sister",
                "sit",
                "six",
                "size",
                "skin",
                "sky",
                "sleep",
                "sleep",
                "slowly",
                "small",
                "smell",
                "smile",
                "snow",
                "so",
                "soft",
                "soil",
                "soldier",
                "solution",
                "some",
                "someone",
                "something",
                "sometimes",
                "son",
                "song",
                "soon",
                "sound",
                "south",
                "southern",
                "space",
                "speak",
                "special",
                "speed",
                "spell",
                "spot",
                "spread",
                "spring",
                "square",
                "stand",
                "star",
                "start",
                "state",
                "statement",
                "stay",
                "steel",
                "step",
                "stick",
                "still",
                "stone",
                "stood",
                "stop",
                "store",
                "story",
                "straight",
                "strange",
                "stream",
                "street",
                "stretch",
                "string",
                "strong",
                "student",
                "study",
                "subject",
                "substance",
                "such",
                "suddenly",
                "suffix",
                "sugar",
                "suggested",
                "sum",
                "summer",
                "sun",
                "supply",
                "suppose",
                "sure",
                "surface",
                "surprise",
                "swim",
                "syllables",
                "symbols",
                "system",
                "table",
                "tail",
                "take",
                "talk",
                "tall",
                "teacher",
                "team",
                "tell",
                "temperature",
                "ten",
                "term",
                "test",
                "than",
                "that",
                "the",
                "their",
                "them",
                "themselves",
                "then",
                "there",
                "these",
                "they",
                "thick",
                "thin",
                "thing",
                "think",
                "third",
                "this",
                "those",
                "though",
                "thought",
                "thousands",
                "three",
                "through",
                "thus",
                "tied",
                "time",
                "tiny",
                "to",
                "today",
                "together",
                "told",
                "tone",
                "too",
                "took",
                "tool",
                "top",
                "total",
                "touch",
                "toward",
                "town",
                "track",
                "trade",
                "train",
                "train",
                "travel",
                "tree",
                "triangle",
                "trip",
                "trouble",
                "truck",
                "true",
                "try",
                "tube",
                "turn",
                "two",
                "type",
                "uncle",
                "under",
                "underline",
                "understand",
                "unit",
                "until",
                "up",
                "upon",
                "us",
                "use",
                "usually",
                "valley",
                "value",
                "various",
                "verb",
                "very",
                "view",
                "village",
                "visit",
                "voice",
                "vowel",
                "wait",
                "walk",
                "wall",
                "want",
                "war",
                "warm",
                "was",
                "wash",
                "Washington",
                "wasn't",
                "watch",
                "water",
                "waves",
                "way",
                "we",
                "wear",
                "weather",
                "week",
                "weight",
                "well",
                "we'll",
                "went",
                "were",
                "west",
                "western",
                "what",
                "wheel",
                "when",
                "where",
                "whether",
                "which",
                "while",
                "white",
                "who",
                "whole",
                "whose",
                "why",
                "wide",
                "wife",
                "wild",
                "will",
                "win",
                "wind",
                "window",
                "wing",
                "winter",
                "wire",
                "wish",
                "with",
                "within",
                "without",
                "woman",
                "women",
                "wonder",
                "won't",
                "wood",
                "word",
                "work",
                "worker",
                "world",
                "would",
                "wouldn't",
                "write",
                "written",
                "wrong",
                "wrote",
                "yard",
                "year",
                "yellow",
                "yes",
                "yet",
                "you",
                "young",
                "your",
                "you're",
                "yourself",

                null};
        return a[tek];
    }
    public String populertr(int tek) {
        String a[]={"bir",
                "yapabilen",
                "hakkında",
                "üstünde",
                "karşısında",
                "hareket, eylem",
                "aksiyon",
                "aslında",
                "eklemek",
                "ek olarak",
                "sıfat",
                "korkmuş",
                "Afrika",
                "sonra",
                "yeniden, yine",
                "karşısında",
                "yaş",
                "önce",
                "anlaşıldı, kararlaştırıldı",
                "önünde",
                "hava",
                "hepsi",
                "izin vermek",
                "neredeyse",
                "yalnız",
                "boyunca",
                "zaten",
                "ayrıca",
                "rağmen",
                "her zaman",
                "gece 12 ile gündüz 12 arası saat dilimi",
                "Amerika",
                "arasında",
                "miktar",
                "bir tek",
                "ve",
                "açı",
                "hayvan",
                "diğer",
                "cevap",
                "herhangi",
                "hiçbir şey",
                "gözükmek",
                "elma",
                "olmak fiili",
                "bölge",
                "kollar",
                "ordu",
                "etraf",
                "varmak (geçmiş zaman)",
                "sanat",
                "iken",
                "sormak",
                "-de, -da",
                "uzak",
                "bebek",
                "arka",
                "kötü",
                "top",
                "banka",
                "temel",
                "olmak",
                "ayı",
                "yenmek",
                "güzel",
                "olmak (geçmiş zaman)",
                "çünkü",
                "olmak",
                "yatak",
                "olmak (geçmiş zaman, pasif)",
                "önce",
                "başlamak (geçmiş zaman)",
                "başlamak",
                "arka",
                "olmak (şimdiki zaman)",
                "inanmak",
                "zil",
                "ait olmak",
                "altında",
                "yanında",
                "en iyi",
                "daha iyi",
                "arasında",
                "büyük",
                "fatura",
                "kuşlar",
                "küçük parça",
                "siyah",
                "engellemek, bloklamak",
                "kan",
                "patlatmak",
                "mavi",
                "tablo",
                "bot",
                "vücut",
                "kemik",
                "kitap",
                "doğmuş",
                "ikisi de",
                "dip",
                "kutu",
                "erkek çocuk",
                "dal",
                "kırmak",
                "parlak",
                "getirmek",
                "Britanyalı",
                "kırık",
                "erkek kardeş",
                "getirilmiş",
                "kahverengi",
                "bina etmek",
                "bina",
                "bina edilmiş",
                "yanmak",
                "işletme",
                "fakat",
                "satın almak",
                "tarafından",
                "aramak",
                "geldi",
                "yapabilmek",
                "yapamamak",
                "yapamamak",
                "başken",
                "yüzbaşı, kaptan",
                "araba",
                "önemsemek",
                "dikkatlice",
                "taşımak",
                "dava, kılıf",
                "kedi",
                "yakalamak",
                "inek",
                "yakalamak (geçmiş zaman)",
                "sebep",
                "hücre",
                "merkez",
                "sent, para birimi",
                "yüzyıl",
                "kesin",
                "şans",
                "değişmek",
                "tablo",
                "kontrol etmek",
                "şef",
                "çocuk",
                "çocuklar",
                "seçmek",
                "kilise",
                "çember",
                "şehir",
                "sınıf",
                "temiz",
                "temizlemek",
                "tırmanmak",
                "kapatmak",
                "elbise",
                "bulut",
                "kıyı",
                "soğuk",
                "renk",
                "kolon",
                "gelmek",
                "ortak",
                "şirket",
                "karşılaştırmak",
                "tamamlanmış",
                "madde",
                "durum",
                "düşünmek",
                "ünsüz harf",
                "içermek",
                "devam etmek",
                "kontrol",
                "pişirmek",
                "soğuk",
                "kopyalamak",
                "mısır",
                "köşe",
                "DOĞRU",
                "masraf",
                "pamuk",
                "yapabilmek (geçmiş zaman)",
                "yapamamak (geçmiş)",
                "saymak",
                "ülke",
                "kurs",
                "kapsamak",
                "inek",
                "oluşturmak",
                "ağlamak",
                "ekin",
                "çapraz",
                "kalabalık",
                "mevcut",
                "kesmek",
                "dans etmek",
                "karanlık",
                "gün",
                "ölü",
                "anlaşma",
                "ölüm",
                "karar vermek",
                "ondalık",
                "derin",
                "açıklamak",
                "çöl",
                "tasarım",
                "ayrıntılar",
                "belirlemek",
                "geliştirmek",
                "sözlük",
                "yaptı",
                "yapmadı",
                "öldü",
                "fark",
                "farklı",
                "zor",
                "direkt",
                "yön",
                "keşfetmek",
                "mesafe",
                "bölünmüş",
                "bölüm",
                "yapmak",
                "doktor",
                "yapmak",
                "yapmamak",
                "köpek",
                "dolar",
                "yapmak (geçmiş)",
                "yapmamak",
                "kapı",
                "aşağı",
                "çizmek",
                "çizim",
                "elbise",
                "araba kullanmak",
                "düşmek",
                "kuru",
                "boyunca",
                "her biri",
                "erken",
                "kulak",
                "toprak, dünya",
                "doğu",
                "kolay",
                "yemek",
                "kenar",
                "etki",
                "yumurta",
                "sekiz",
                "ikisi de",
                "elektrik",
                "element",
                "diğer",
                "son",
                "enerji",
                "motor",
                "İngiltere",
                "İngiliz",
                "eğlenmek",
                "yeterli",
                "girmek",
                "tüm",
                "eşit",
                "denklem",
                "özellikle",
                "Avrupa",
                "eşit",
                "akşam",
                "hep",
                "hepsi",
                "herkes",
                "her şey",
                "aynen",
                "örnek",
                "hariç",
                "heyecan verici",
                "egzersiz",
                "beklemek, ummak",
                "tecrübe",
                "deney",
                "açıklamak",
                "ekspres",
                "göz",
                "yüz",
                "gerçek",
                "fabrika",
                "faktörler",
                "düşmek",
                "aile",
                "ünlü",
                "uzak",
                "çiftlik",
                "çiftçi",
                "hızlı",
                "baba",
                "korku",
                "hissetmek",
                "his",
                "ayaklar",
                "düşmüş",
                "hissetmiş",
                "birkaç",
                "alan",
                "incir",
                "kavga",
                "figür",
                "doldurulmuş",
                "nihayetinde",
                "bulmak",
                "iyi",
                "parmaklar",
                "bitmiş",
                "ateş",
                "birinci",
                "balık",
                "uymak",
                "beş",
                "düz",
                "zemin",
                "akmak",
                "çiçekler",
                "uçmak",
                "takip etmek",
                "yemek",
                "ayak",
                "için",
                "güç",
                "orman",
                "yapı",
                "ileri",
                "bulunmuş",
                "dört",
                "parça",
                "Fransa",
                "bedava",
                "Fransız",
                "taze",
                "arkadaşlar",
                "tarafından",
                "ön",
                "meyve",
                "tam",
                "eğlence",
                "oyun",
                "bahçe",
                "gaz",
                "verdi",
                "genel",
                "almak",
                "kız",
                "vermek",
                "cam",
                "gitmek",
                "tanrı",
                "altın",
                "gitmiş",
                "güzel",
                "sahip olmak",
                "hükümet",
                "çimen",
                "müthiş",
                "Yunan",
                "yeşil",
                "büyümüş",
                "zemin",
                "grup",
                "büyümek",
                "tahmin etmek",
                "silah",
                "sahip olmak (geçmiş)",
                "saç",
                "durmak",
                "el",
                "olmak",
                "mutlu",
                "zor",
                "sahip olmak",
                "şapka",
                "sahip olmak",
                "erkek",
                "baş",
                "duymak",
                "duydu",
                "kalp",
                "ısı",
                "ağır",
                "tutmak (geçmiş)",
                "yardım",
                "O (kadın)",
                "burada",
                "yüksek",
                "tepe",
                "O (erkek)",
                "kendisi (erkek)",
                "onun (erkek)",
                "tarih",
                "vurmak",
                "tutmak",
                "delik",
                "ev",
                "umut",
                "at",
                "sıcak",
                "saat",
                "ev",
                "nasıl",
                "ancak",
                "dev",
                "insan",
                "yüz (sayı)",
                "avlanma",
                "ben",
                "buz",
                "fikir",
                "eğer",
                "ben (gelecekte)",
                "önemli",
                "içeri",
                "inç (uzunluk birimi)",
                "içermek",
                "yükselmek",
                "Hindistanlı",
                "göstermek",
                "endüstri",
                "bilgi",
                "böcek",
                "içinde",
                "yerine",
                "enstruman",
                "ilgi",
                "ilginç",
                "içine",
                "demir",
                "olmak",
                "ada",
                "olmamak",
                "o (hayvan veya cansız)",
                "onun",
                "olmak (hayvan veya cansız)",
                "kendisi (hayvan veya cansız)",
                "Japon",
                "iş",
                "katılmak",
                "zıplamak",
                "sadece",
                "saklamak",
                "saklanmış",
                "anahtar",
                "öldürmek",
                "kibar",
                "kral",
                "bilmek (geçmiş)",
                "bilmek",
                "bilinmiş",
                "kadın",
                "göl",
                "arazi",
                "dil",
                "geniş",
                "son",
                "sonra",
                "gülmek",
                "kanun",
                "uzanmak",
                "kurşun",
                "öğrenmek",
                "en azı",
                "terketmek",
                "önderlik etmek (geçmiş)",
                "sol",
                "ayak",
                "uzunluk",
                "az",
                "izin vermek",
                "haydi",
                "mektup",
                "seviye",
                "yalan söylemek",
                "hayat",
                "kaldırmak",
                "ışık",
                "beğenmek",
                "çizgi",
                "liste",
                "dinlemek",
                "küçük",
                "yaşamak",
                "lokasyon",
                "uzun",
                "bakmak",
                "kayıp",
                "çok",
                "gürültülü",
                "sevmek",
                "düşük",
                "makine",
                "yapılmış",
                "ana",
                "majör",
                "yapmak",
                "erkek",
                "çok",
                "harita",
                "mart",
                "işaret",
                "maç",
                "materyal",
                "madde",
                "belki",
                "belki",
                "ben",
                "anlam",
                "ölçü",
                "et",
                "tanışmak",
                "melodi",
                "üye",
                "erkekler",
                "metal",
                "metot",
                "orta",
                "belki",
                "mil",
                "süt",
                "milyon",
                "akıl",
                "maden",
                "dakika",
                "özlemek",
                "modern",
                "molekül",
                "an",
                "para",
                "ay",
                "ay",
                "daha",
                "gündüz",
                "en fazla",
                "anne",
                "dağ",
                "ağız",
                "hareket etmek",
                "hareket",
                "fazla",
                "müzik",
                "zorunda olmak",
                "benim",
                "isim",
                "millet",
                "doğal",
                "yanında",
                "gerekli",
                "ihtiyaç duymak",
                "asla",
                "yeni",
                "sonraki",
                "gece",
                "hayır",
                "veya (olumsuz)",
                "kuzey",
                "kuzeyli",
                "burun",
                "hayır",
                "not",
                "hiçbir şey",
                "farketmek",
                "isim",
                "şimdi",
                "sayı",
                "sayısal",
                "obje",
                "gözlemlemek",
                "okyanus",
                "-den, -dan",
                "kapalı",
                "ofis",
                "sıkça",
                "oh",
                "petrol, yağ",
                "yaşlı",
                "açık",
                "bir kere",
                "bir",
                "sadece",
                "açık",
                "zıt",
                "veya",
                "düzen",
                "diğer",
                "bizim",
                "dışarı",
                "dışarısı",
                "üzerinde",
                "sahip olmak",
                "oksijen",
                "sayfa",
                "boyamak",
                "çift",
                "kağıt",
                "paragraf",
                "park",
                "bölüm",
                "belli",
                "parti",
                "geçmiş",
                "geçmiş",
                "patern",
                "ödemek",
                "insanlar",
                "başına",
                "belki",
                "nokta",
                "insan",
                "cümle parçası",
                "seçmek",
                "resim",
                "parça",
                "yer",
                "düz",
                "plan",
                "uçak",
                "bitki",
                "bitkiler",
                "oynamak",
                "lütfen",
                "çoğul",
                "şiir",
                "puan",
                "kutup",
                "fakir",
                "pozisyon",
                "mümkün",
                "ağırlık birimi",
                "güç",
                "pratik",
                "hazırlanmak",
                "başkan",
                "güzel",
                "yazılmış",
                "belki",
                "sorun",
                "işlem",
                "üretmek",
                "ürün",
                "mülk",
                "sağlamak",
                "çekmek",
                "itmek",
                "koymak",
                "soru",
                "hızlıca",
                "sessiz",
                "oldukça",
                "yarış",
                "radyo",
                "yağmur",
                "yükseltmek",
                "koşmak (geçmiş)",
                "-dense",
                "ulaşmak",
                "okumak",
                "hazır",
                "gerçekten",
                "sebep",
                "almak",
                "kayıt",
                "kırmızı",
                "bölge",
                "kalan",
                "hatırlamak",
                "tekrar etmek",
                "rapor",
                "temsil etmek",
                "gücenmek",
                "dinlenmek",
                "sonuç",
                "dönmek",
                "ritim",
                "zengin",
                "binmek",
                "sağ",
                "zil çalmak",
                "yükselmek",
                "nehir",
                "yol",
                "kaya",
                "yuvarlanmış",
                "oda",
                "kök",
                "halat",
                "gül",
                "yuvarlak",
                "satır",
                "kural",
                "koşmak",
                "güvenli",
                "dedi",
                "yelken açmak",
                "aynı",
                "kum",
                "oturdu",
                "kurtarmak",
                "testere",
                "söylemek",
                "ölçek",
                "okul",
                "bilim",
                "bilim adamı",
                "skor",
                "deniz",
                "koltuk",
                "saniye",
                "bölüm",
                "görmek",
                "tohumlar",
                "görünmek",
                "görünmek",
                "satmak",
                "göndermek",
                "his",
                "gönderilmiş",
                "cümle",
                "ayrı",
                "hizmet etmek",
                "ayarlamak",
                "ayarlanmış",
                "yedi",
                "birkaç",
                "olsun",
                "şekil",
                "keskin",
                "O (kadın)",
                "gemi",
                "ayakkabı",
                "dükkan",
                "kısa",
                "zorunda olmak",
                "omuz",
                "bağırmak",
                "göstermek",
                "gösterilmiş",
                "yan",
                "görüş",
                "işaret",
                "sinyal",
                "sessiz",
                "benzer",
                "basit",
                "-den beri",
                "şarkı söylemek",
                "efendi",
                "kız kardeş",
                "oturmak",
                "altı",
                "boyut",
                "deri",
                "hava",
                "uyku",
                "uyku",
                "yavaşça",
                "küçük",
                "koklamak",
                "gülümsemek",
                "kar",
                "şöyle",
                "yumuşak",
                "toprak",
                "asker",
                "çözüm",
                "bazı",
                "birisi",
                "bir şey",
                "bazen",
                "erkek çocuk",
                "şarkı",
                "yakında",
                "ses",
                "güney",
                "güneyli",
                "uzay, boşluk",
                "konuşmak",
                "özel",
                "hız",
                "hecelemek",
                "nokta",
                "yayılmak",
                "ilkbahar",
                "kare",
                "ayakta durmak",
                "yıldız",
                "başlamak",
                "durum",
                "ifade",
                "kalmak",
                "çelik",
                "adım",
                "yapışmak",
                "halen",
                "taş",
                "ayakta durmuş",
                "durmak",
                "dükkan",
                "hikaye",
                "düz",
                "garip",
                "akıntı",
                "sokak",
                "genişletmek",
                "dizi",
                "güçlü",
                "öğrenci",
                "çalışmak",
                "konu",
                "madde",
                "örneğin",
                "aniden",
                "son ek",
                "şeker",
                "tavsiye edilmiş",
                "özet",
                "yaz",
                "güneş",
                "malzeme",
                "tahmin yürütmek",
                "emin",
                "yüzey",
                "süpriz",
                "yüzmek",
                "ders programı",
                "sembol",
                "sistem",
                "masa",
                "kuyruk",
                "almak",
                "konuşmak",
                "uzun",
                "öğretmen",
                "takım",
                "söylemek",
                "sıcaklık",
                "on",
                "dönem",
                "denemek",
                "-den",
                "o (eşya)",
                "o",
                "onların",
                "onlar",
                "onların kendisi",
                "sonra",
                "orada",
                "bunlar",
                "onlar (insan)",
                "kalın",
                "ince",
                "şey",
                "düşünmek",
                "üçüncü",
                "o",
                "onlar",
                "-e rağmen",
                "düşünce",
                "binlerce",
                "üç",
                "arasından",
                "nitekim",
                "bağlı",
                "zaman",
                "küçücük",
                "ona",
                "bugün",
                "birlikte",
                "söyledi",
                "ton",
                "çok",
                "almak (geçmiş zaman)",
                "alet",
                "üst",
                "toplam",
                "dokunmak",
                "-e doğru",
                "yerleşke",
                "takip etmek",
                "ticaret",
                "tren",
                "eğitmek",
                "yolculuk",
                "ağaç",
                "üçgen",
                "yolculuk",
                "sorun",
                "kamyon",
                "DOĞRU",
                "denemek",
                "tüp",
                "dönüş",
                "iki",
                "yazmak",
                "amca",
                "altında",
                "altı çizili",
                "anlamak",
                "ünite",
                "-e kadar",
                "yukarı",
                "üstüne",
                "biz",
                "kullanmak",
                "genellikle",
                "vadi",
                "değer",
                "çeşitli",
                "fiil",
                "çok",
                "görüş",
                "köy",
                "ziyaret",
                "ses",
                "sesli harf",
                "beklemek",
                "yürümek",
                "duvar",
                "istemek",
                "savaş",
                "sıcak",
                "olmak (geçmiş)",
                "yıkamak",
                "Washington",
                "olmamak (geçmiş)",
                "izlemek",
                "su",
                "dalgalar",
                "yol",
                "biz",
                "giymek",
                "hava",
                "hafta",
                "kilo",
                "iyi",
                "biz (gelecek zaman)",
                "gitmek (geçmiş)",
                "olmak (çoğul, geçmiş)",
                "batı",
                "batılı",
                "ne?",
                "tekerlek",
                "ne zaman?",
                "nerede?",
                "eğer",
                "hangisi?",
                "süresince",
                "beyaz",
                "kim?",
                "bütün",
                "kimin?",
                "neden?",
                "geniş",
                "eş (kadın)",
                "vahşi",
                "istek",
                "kazanmak",
                "rüzgar",
                "pencere",
                "kanat",
                "kış",
                "kablo",
                "dilemek",
                "birlikte",
                "içinde",
                "olmadan",
                "kadın",
                "kadınlar",
                "merak etmek",
                "olmamak (gelecek)",
                "ağaç",
                "kelime",
                "iş",
                "işçi",
                "dünya",
                "istemek",
                "istememek",
                "yazmak",
                "yazılı",
                "YANLIŞ",
                "yazmak (geçmiş)",
                "bahçe",
                "yıl",
                "sarı",
                "evet",
                "henüz",
                "sen",
                "genç",
                "senin",
                "sen (olmak)",
                "kendin",

                null};
        return a[tek];
    }
    public String sayitr(int tek) {
        String a[]={"Sıfır","Bir","İki","Üç","Dört","Beş","Altı","Yedi","Sekiz","Dokuz","On",null};
        return a[tek];
    }
    public String sayien(int tek) {
        String a[]={"Zero","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten",null};
        return a[tek];
    }
    public String hayvantr(int tek) {
        String a[]={"Köpek","Kedi","Papağan","Balık","Kuş","Tavşan","Kaplumbağa","İnek","Eşek","At","Koyun","Keçi","Domuz","Horoz","Tavuk","Kaz","Ördek","Hindi","Kelebek","Arı","Kurbağa","Penguen","Koala","Geyik","Kurt","Panda","Tilki","Kanguru","Sincap","Kirpi","Maymun","Tavuskuşu","Gergedan","Su aygırı","Ayı","Zebra","Kertenkele","Timsah","Yunus","Köpek balığı","Yılan","Fil","Zürafa",null};
        return a[tek];
    }
    public String hayvanen(int tek) {
        String a[]={"Dog","Cat","Parrot","Fish","Bird","Rabbit","Turtle","Cow","Donkey","Horse","Sheep","Goat","Pig","Roaster","Chicken","Goose","Duck","Turkey","Butterfly","Bee","Frog","Penguin","Koala","Deer","Wolf","Panda","Fox","Kangaroo","Squirrel","Hedgehog","Monkey","Peacock","Rhino","Hippo","Bear","Zebra","Lizard","Crocodile","Dolphin","Shark","Snake","Elephant","Giraffe",null};
        return a[tek];
    }
    public String takvimtr(int tek) {
        String a[]={"Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık",null};
        return a[tek];
    }
    public String takvimen(int tek) {
        String a[]={"January","February","March","April","May","June","July","August","September","October","November","December",null};
        return a[tek];
    }
    public String birlesmistr(int tek) {
        String a[]={"Kırmızı","Mavi","Yeşil","Sarı","Pembe","Mor","Siyah","Kahverengi","Turuncu","Beyaz","Gri",
                "Sıfır","Bir","İki","Üç","Dört","Beş","Altı","Yedi","Sekiz","Dokuz","On",
                "Köpek","Kedi","Papağan","Balık","Kuş","Tavşan","Kaplumbağa","İnek","Eşek","At","Koyun","Keçi",
                "Domuz","Horoz","Tavuk","Kaz","Ördek","Hindi","Kelebek","Arı","Kurbağa","Penguen","Koala","Geyik",
                "Kurt","Panda","Tilki","Kanguru","Sincap","Kirpi","Maymun","Tavuskuşu","Gergedan","Su aygırı","Ayı",
                "Zebra","Kertenkele","Timsah","Yunus","Köpek balığı","Yılan","Fil","Zürafa",
                "Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık"
                ,null};
        return a[tek];
    }
    public String birlesmisen(int tek) {
        String a[]={"Red","Blue","Green","Yellow","Pink","Purple","Black","Brown","Orange","White","Gray",
                "Zero","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten",
                "DOG","CAT","PARROT","FISH","BIRD","RABBIT","TURTLE","COW","DONKEY","HORSE","SHEEP","GOAT","PIG","ROOSTER","CHICKEN",
                "GOOSE","DUCK","TURKEY","BUTTERFLY","BEE","FROG","PENGUIN","KOALA","DEER","WOLF","PANDA","FOX","KANGAROO","SQUIRREL",
                "HEDGEHOG","MONKEY","PEACOCK","RHINO","HIPPO","BEAR","ZEBRA","LIZARD","CROCODILE","DOLPHIN","SHARK","SNAKE","ELEPHANT","GIRAFFE",
                "January","February","March","April","May","June","July","August","September","October","Novamber","December"
                ,null};
        return a[tek];
    }
    public String cumlesoru(int tek) {
        String a[]={"The boy ................ the little child while passing across the road.", "You can ...............your mobile phone to the computer via a cable.",
                "The bill covers drinks, it also ..........  desserts.",
               "I have ...........  my English certificate along with my application form.",
              "The manager has ..........  the failure to his partner's indefference. ",
                "The workers ............  in the conference hall for the weekly relaxation therapy.",
                "I am not eager to .............  in your fight. ",
                "A nice, white cat .......  me home and I decided to keep it.",
                "The police had been  ............ Jim for two years when they finally arrested him.",
             "When my brother ran down the hill, I started to .........  him.",null};

        return a[tek];
    }
    public String cumlecevap(int tek) {
        String a[]={"accompanied","connect","includes","enclosed","related","assemble",
                "involve","chased","pursuing","follow",null};
        return a[tek];
    }
    public String bosluksoru(int tek) {
        String a[]={
        "________ often do you go to the cinema?",
        "________ does Tarkan live?",
        "________ does your university year start?",
        "________ do you like talking to?",
        "________ does a normal day at university finish?",
        "________ is the capital of Uzbekistan?",
        "________ has your jacket?",
        "________ do some people hate studying English?",
        "________ is your maths class? - It's at 10 o'clock.",
        "________ is it? - It's in the fridge.",
        "________ t-shirts are there in your bag? - There are 10 t-shirts in my bag.",
        "________ likes Diana? - Kevin likes her.",
        "________ is your match? - It's at 6.",
        "________ are you? - Fine, you?",
        "________ are the kids? - They are in the backyard.",
        "________ your sister’s birthday? - It's next Monday.",
        "________ do you want a sandwich? - Because I'm hungry.",
        "________ is she from? - She's from Japan."
                ,null};

        return a[tek];
    }
    public String boslukcevap(int tek) {
        String a[]={"How","Where","When","Who","When","What","Who","Why","When","Where","How many","Who"
                ,"What time","How","Where","When","Why","Where"
                ,null};
        return a[tek];
    }





}


